# Generated by Django 5.2.2 on 2026-01-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_codigo', models.CharField(max_length=20)),
                ('cliente_loja', models.CharField(max_length=10)),
                ('cliente_nome', models.CharField(max_length=100)),
                ('data_acordo', models.DateField()),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('tipo_acordo', models.CharField(choices=[('valor', 'Por Valor'), ('produto', 'Por Produto')], max_length=20)),
                ('valor_acordo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodicidade', models.IntegerField(blank=True, help_text='Meses', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcordoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(max_length=20)),
                ('produto_descricao', models.CharField(max_length=100)),
                ('qtd_faturada', models.IntegerField(blank=True, null=True)),
                ('qtd_bonificada', models.IntegerField(blank=True, null=True)),
                ('qtd_mensal', models.IntegerField(blank=True, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.acordocomercial')),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=15, verbose_name='Plataforma')),
                ('tipo_cliente', models.CharField(max_length=20, verbose_name='Tipo')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cgc', models.CharField(max_length=20, verbose_name='CGC')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('grupo_cliente', models.CharField(max_length=100, verbose_name='Grupo de Cliente')),
                ('condicao_pagamento', models.CharField(max_length=100, verbose_name='Condição de Pagamento')),
                ('condicao_pagamento_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('entrega_cep', models.CharField(max_length=9, verbose_name='CEP Entrega')),
                ('entrega_estado', models.CharField(max_length=2, verbose_name='Estado Entrega')),
                ('entrega_cidade', models.CharField(max_length=100, verbose_name='Cidade Entrega')),
                ('entrega_bairro', models.CharField(max_length=100, verbose_name='Bairro Entrega')),
                ('entrega_endereco', models.CharField(max_length=255, verbose_name='Endereço Entrega')),
                ('entrega_numero', models.CharField(max_length=20, verbose_name='Número Entrega')),
                ('entrega_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horário de Entrega')),
                ('socio_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('socio_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('socio_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('socio_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('socio_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('socio_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('socio_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('socio_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('socio_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('finan_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('finan_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('compra_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('compra_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CADASTRADO', 'Cadastrado no ERP'), ('LIBERADO', 'Liberado para Venda'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro de Cliente',
                'verbose_name_plural': 'Cadastros de Clientes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='AnexoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='cadastros/anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cadastros.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='VerbaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês de Referência')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('percentual_limite_por_cliente', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentual máximo da verba total que pode ser usado em um único cliente', max_digits=5)),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_realizados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verba Mensal',
                'verbose_name_plural': 'Verbas Mensais',
            },
        ),
    ]
