# Generated by Django 5.2.2 on 2026-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_verbamensal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordocomercial',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa do Acordo'),
        ),
    ]
