# Generated by Django 5.2.2 on 2026-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_acordocomercial_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordocomercial',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=15),
        ),
    ]
