# Generated by Django 5.2.2 on 2026-01-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VERBA_VENDEDOR', 'Verba Vendedor'), ('ACORDO_COMERCIAL', 'Acordo Comercial'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial')], max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('cliente_codigo', models.CharField(max_length=15)),
                ('cliente_loja', models.CharField(max_length=2)),
                ('cliente_razao_social', models.CharField(max_length=100)),
                ('cliente_nome_fantasia', models.CharField(max_length=100)),
                ('cliente_cpf_cnpj', models.CharField(max_length=18)),
                ('cliente_grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('justificativa', models.TextField(verbose_name='Observação/Justificativa')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=15)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacao_reprovacao', models.TextField(blank=True, null=True)),
                ('pedido_protheus', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonificação',
                'verbose_name_plural': 'Bonificações',
            },
        ),
        migrations.CreateModel(
            name='BonificacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(max_length=15)),
                ('produto_descricao', models.CharField(max_length=100)),
                ('preco_tabela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='solicitacoes.bonificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20)),
                ('loja_cliente', models.CharField(max_length=50)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('TECNICO', 'PLANTÃO TÉCNICO'), ('REPOSICAO', 'PLANTÃO DE REPOSIÇÃO')], max_length=20)),
                ('ocorrencia', models.CharField(choices=[('CHOPEIRA', 'CHOPEIRA'), ('MANOMETRO', 'MANÔMETRO'), ('CILINDRO', 'CILINDRO'), ('EXTRATORA', 'EXTRATORA'), ('TROCA_BARRIL', 'TROCA DE BARRIL'), ('ENTREGA_BARRIL', 'ENTREGA DE BARRIL'), ('OUTRO', 'OUTRO')], max_length=50)),
                ('ocorrencia_outro', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('taxa', models.BooleanField(default=False)),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horario', models.TimeField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado')], default='PENDENTE', max_length=20)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
