# Generated by Django 5.2.10 on 2026-01-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacao',
            name='cliente_loja',
            field=models.CharField(max_length=4),
        ),
    ]
