# Generated by Django 5.2.2 on 2026-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_bonificacao_cliente_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificacao',
            name='data_entrega_retirada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonificacao',
            name='foto_sac',
            field=models.ImageField(blank=True, null=True, upload_to='bonificacoes/sac/'),
        ),
        migrations.AddField(
            model_name='bonificacao',
            name='metodo_entrega',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bonificacao',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('CIEC', 'CIEC'), ('ISLA', 'ISLA'), ('WRP', 'WRP')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bonificacao',
            name='tipo',
            field=models.CharField(choices=[('VERBA_VENDEDOR', 'Verba Vendedor'), ('ACORDO_COMERCIAL', 'Acordo Comercial'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial'), ('SAC', 'SAC')], max_length=20),
        ),
    ]
