# Generated by Django 5.2.2 on 2026-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_bonificacao_data_entrega_retirada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='zenvia_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
    ]
