# Generated by Django 5.2.2 on 2026-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_plantao_zenvia_message_id_alter_plantao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=15),
        ),
    ]
