# Generated by Django 5.2.2 on 2026-05-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_acordocomercial_situacao'),
        ('solicitacoes', '0005_alter_bonificacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificacaoitem',
            name='acordo_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilizacoes_diretas', to='cadastros.acordocomercial'),
        ),
    ]
