# Generated by Django 5.2.2 on 2026-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_bonificacaoitem_acordo_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacao',
            name='tipo',
            field=models.CharField(choices=[('VERBA_VENDEDOR', 'Verba Vendedor'), ('ACORDO_COMERCIAL', 'Acordo Comercial'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial'), ('SAC', 'SAC'), ('ATIVACAO', 'Ativação de Marca')], max_length=20),
        ),
    ]
