# Generated by Django 5.2.2 on 2026-09-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_alter_bonificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacao',
            name='tipo',
            field=models.CharField(choices=[('VERBA_VENDEDOR', 'Verba Vendedor'), ('ACORDO_COMERCIAL', 'Acordo Comercial'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial'), ('SAC', 'SAC'), ('ATIVACAO_MARCA', 'Ativação de Marca')], max_length=20),
        ),
        migrations.CreateModel(
            name='FotoBonificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='sac/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('bonificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='solicitacoes.bonificacao')),
            ],
        ),
    ]
