# Generated by Django 5.2.2 on 2026-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_alter_bonificacao_tipo_fotobonificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacao',
            name='tipo',
            field=models.CharField(choices=[('VERBA_VENDEDOR', 'Verba Vendedor'), ('ACORDO_COMERCIAL', 'Acordo Comercial'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial'), ('SAC', 'SAC'), ('ATIVACAO_MARCA', 'Ativação de Marca'), ('MARKETING', 'Marketing')], max_length=20),
        ),
    ]
