# Generated by Django 5.2.2 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('payload_bruto', models.JSONField()),
                ('status_processamento', models.CharField(default='Recebido', max_length=20)),
            ],
        ),
    ]
