# Generated by Django 5.2.2 on 2025-06-16 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=15, verbose_name='Plataforma')),
                ('tipo_cliente', models.CharField(max_length=20, verbose_name='Tipo')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cgc', models.CharField(max_length=20, verbose_name='CGC')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('grupo_cliente', models.CharField(max_length=150, verbose_name='Grupo Cliente')),
                ('condicao_pagamento', models.CharField(max_length=20, verbose_name='Condição de Pagamento')),
                ('horario_entrega', models.CharField(max_length=20, verbose_name='Horário Entrega')),
                ('nome_socio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Sócio')),
                ('cpf_socio', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Sócio')),
                ('cep_socio', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Sócio')),
                ('estado_socio', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado do Sócio')),
                ('cidade_socio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade do Sócio')),
                ('bairro_socio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do Sócio')),
                ('endereco_socio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Sócio')),
                ('numero_socio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número do Sócio')),
                ('complemento_socio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do Sócio')),
                ('nome_financeiro', models.CharField(blank=True, null=True, verbose_name='Nome Financeiro')),
                ('telefone_financeiro', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Financeiro')),
                ('nome_compras', models.CharField(blank=True, null=True, verbose_name='Nome Compras')),
                ('telefone_compras', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Compras')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('cadastrado', 'Cadastrado'), ('liberado', 'Liberado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status do Cadastro')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='AnexoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='cadastros/anexos_especificos/', verbose_name='Arquivo Anexado')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Anexo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='salesapp.cadastro', verbose_name='Cadastro Relacionado')),
            ],
            options={
                'verbose_name': 'Anexo de Cadastro',
                'verbose_name_plural': 'Anexos de Cadastros',
                'ordering': ['-data_upload'],
            },
        ),
    ]
