# Generated by Django 5.2.2 on 2025-07-20 23:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(max_length=20, verbose_name='Código do Cliente')),
                ('loja_cliente', models.CharField(max_length=4, verbose_name='Loja do Cliente')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cgc', models.CharField(max_length=18, verbose_name='CNPJ/CPF')),
                ('grupo_cliente', models.CharField(max_length=50, verbose_name='Grupo do Cliente')),
                ('motivo', models.TextField(verbose_name='Motivo da Bonificação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('numero_pedido', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pedido de Venda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_aprovacao_gestor', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação do Gestor')),
                ('obs_gestor', models.TextField(blank=True, null=True, verbose_name='Observação do Gestor')),
                ('data_aprovacao_diretoria', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação da Diretoria')),
                ('obs_diretoria', models.TextField(blank=True, null=True, verbose_name='Observação da Diretoria')),
                ('data_pedido', models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do Pedido')),
                ('obs_pedido', models.TextField(blank=True, null=True, verbose_name='Observação do Pedido')),
                ('motivo_recusa', models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa')),
                ('status', models.CharField(choices=[('PENDENTE_GESTOR', 'Pendente Aprovação Gestor'), ('PENDENTE_DIRETORIA', 'Pendente Aprovação Diretoria'), ('PENDENTE_PEDIDO', 'Pendente Lançamento do Pedido'), ('RECUSADA', 'Recusada'), ('PEDIDO_GERADO', 'Pedido Gerado')], default='PENDENTE_GESTOR', max_length=50, verbose_name='Status')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável')),
            ],
            options={
                'verbose_name': 'Bonificação',
                'verbose_name_plural': 'Bonificações',
            },
        ),
        migrations.CreateModel(
            name='ItemBonificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('desc_produto', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('preco_tabela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Tabela')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_total_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Item')),
                ('bonificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='salesapp.bonificacao', verbose_name='Bonificação Relacionada')),
            ],
            options={
                'verbose_name': 'Item de Bonificação',
                'verbose_name_plural': 'Itens de Bonificação',
            },
        ),
        migrations.AddIndex(
            model_name='bonificacao',
            index=models.Index(fields=['cod_cliente', 'loja_cliente'], name='salesapp_bo_cod_cli_58b29c_idx'),
        ),
    ]
