# Generated by Django 5.2.2 on 2025-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='bairro_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cidade_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='complemento_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='condicao_pagamento_detalhe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhe da Condição de Pagamento (Outro)'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='endereco_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nome_fantasia',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='numero_entrega',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Entrega'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usar_dados_socio_comprador',
            field=models.BooleanField(default=False, verbose_name='Usar Dados Sócio (Comprador)'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usar_dados_socio_financeiro',
            field=models.BooleanField(default=False, verbose_name='Usar Dados Sócio (Financeiro)'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usar_endereco_cadastrado',
            field=models.BooleanField(default=False, verbose_name='Usar Endereço Cadastrado'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_compras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Compras'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_financeiro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Financeiro'),
        ),
    ]
