# Generated by Django 5.2.3 on 2025-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='data_aprovacao_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação Cadastro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_aprovacao_financeiro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação Financeiro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='obs_cadastro',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Cadastro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='obs_financeiro',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Financeiro'),
        ),
    ]
