# Generated by Django 5.2.2 on 2025-07-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_bonificacao_itembonificacao_and_more'),
        ('salesapp', '0002_cadastro_data_aprovacao_cadastro_and_more'),
    ]

    operations = [
    ]
