# Generated by Django 5.2.2 on 2025-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_merge_20250721_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificacao',
            name='tipo_bonificacao',
            field=models.CharField(choices=[('VERBA_CONTRATO', 'Verba Contrato'), ('BONIFICACAO_VERBA', 'Bonificação Dentro da Verba'), ('NEGOCIACAO_ESPECIAL', 'Negociação Especial')], default='NEGOCIACAO_ESPECIAL', max_length=50),
        ),
    ]
