# Generated by Django 5.2.2 on 2026-03-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVerba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fornecedor', models.CharField(choices=[('EXISTENTE', 'Cadastrado no Protheus'), ('NOVO', 'Novo Fornecedor / Sem Cadastro')], default='EXISTENTE', max_length=10)),
                ('fornecedor_codigo', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Protheus')),
                ('fornecedor_loja', models.CharField(blank=True, max_length=2, null=True, verbose_name='Loja Protheus')),
                ('fornecedor_nome_razao', models.CharField(max_length=255, verbose_name='Razão Social / Nome')),
                ('fornecedor_cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('produto_servico', models.CharField(max_length=255, verbose_name='Produto ou Serviço')),
                ('categoria', models.CharField(choices=[('REPARO_ESTRUTURA', 'Reparo de Estrutura'), ('SERVICO_TERCEIRO', 'Serviços de Terceiros'), ('MANUTENCAO_MAQ', 'Manutenção de Máquinas'), ('INSUMOS_ADITI', 'Insumos / Aditivos'), ('LOGISTICA', 'Logística e Frete'), ('OUTROS', 'Outros')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto')], max_length=50)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tem_documento', models.BooleanField(default=False, verbose_name='Possui Nota/Comprovante?')),
                ('arquivo_nota', models.FileField(blank=True, null=True, upload_to='solicitacoes/verba/notas/%Y/%m/', verbose_name='Arquivo da Nota Fiscal')),
                ('arquivo_boleto', models.FileField(blank=True, null=True, upload_to='solicitacoes/verba/boletos/%Y/%m/', verbose_name='Arquivo do Boleto')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('obs_aprovacao', models.TextField(blank=True, verbose_name='Observações da Aprovação/Reprovação')),
                ('usuario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Verba',
                'verbose_name_plural': 'Solicitações de Verba',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
