# Generated by Django 5.2.2 on 2026-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoverba',
            name='fornecedor_codigo',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código Protheus'),
        ),
        migrations.AlterField(
            model_name='solicitacaoverba',
            name='fornecedor_loja',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Loja Protheus'),
        ),
    ]
