# Generated by Django 5.2.2 on 2026-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_solicitacaoverba_fornecedor_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoverba',
            name='num_titulo',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Número do Título Protheus'),
        ),
        migrations.AlterField(
            model_name='solicitacaoverba',
            name='categoria',
            field=models.CharField(choices=[('CONFRATERNIZACAO', 'Confraternização'), ('DESPESA_VIAGEM', 'Despesas de Viagem'), ('DESPESA_ECOMMERCE', 'Despesas Ecommerce'), ('EVENTOS', 'Eventos'), ('FRETE', 'Frete'), ('LOCACAO_EQUIPAMENTOS', 'Locação de Equipamentos'), ('MANUTENCAO_INDUSTRIAL', 'Manutenção e Conservação'), ('MANUTENCAO_EQUIPAMENTO', 'Manutenção de Equipamentos'), ('MANUTENCAO_VEICULOS', 'Manutenção de Veículos'), ('MARKETING', 'Marketing'), ('PLANTAO', 'Plantão'), ('SERVICO_TERCEIRO', 'Serviço de Terceiros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaoverba',
            name='forma_pagamento',
            field=models.CharField(choices=[('BOLETO', 'Boleto'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência')], max_length=50),
        ),
    ]
