# Generated by Django 5.2.2 on 2026-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_solicitacaoverba_num_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoverba',
            name='obs_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Aprovação/Reprovação'),
        ),
    ]
